import type { SongType } from '@/types/song'

export const SONGS: SongType[] = [
  {
    id: '1',
    albumId: '1',
    name: 'Can You Feel It',
    singer: 'Jean Roch',
    youtubeId: '7eQHIGZfw6I',
  },
  {
    id: '2',
    albumId: '1',
    name: 'If You',
    singer: 'Magic Box',
    youtubeId: 'mN9ZEQfJuO8',
  },
  {
    id: '3',
    albumId: '1',
    name: 'California Dreaming (Tek-House Single)',
    singer: 'Royal Gigolos',
    youtubeId: 'N4TqpTTwsNo',
  },
  {
    id: '4',
    albumId: '1',
    name: 'Dragostea Din Tei (DJ Ross Remix)',
    singer: 'O-Zone',
    youtubeId: '_i6eSoHJQro',
  },
  {
    id: '5',
    albumId: '1',
    name: 'Saturday Night (DJ Frank Remix)',
    singer: 'The Underdog Project',
    youtubeId: '3GCaVIbUTyg',
  },
  {
    id: '6',
    albumId: '1',
    name: 'Push The Feeling On 2003 (J.C.A. Remix)',
    singer: 'Nightcrawlers',
    youtubeId: 'Gs1OU3kLiSc',
  },
  {
    id: '7',
    albumId: '1',
    name: 'Call On Me',
    singer: 'Eric Prydz',
    youtubeId: 'qetW6R9Jxs4',
  },
  {
    id: '8',
    albumId: '1',
    name: 'Pump It Up!',
    singer: 'Danzel',
    youtubeId: '0HtyF0jux2Q',
  },
  {
    id: '9',
    albumId: '1',
    name: 'Fuck It (I Don`t Want You Back)',
    singer: 'Florida Inc.',
    youtubeId: 'L9QukEdhIww',
  },
  {
    id: '10',
    albumId: '1',
    name: 'Smells Like Teen Spirit',
    singer: 'Happening',
    youtubeId: 'kfQOiW591pQ',
  },
  {
    id: '11',
    albumId: '1',
    name: 'Seven Nation Army',
    singer: 'Arena',
    youtubeId: 'VSQfTAxVf48',
  },
  {
    id: '12',
    albumId: '1',
    name: 'He`s A Dream',
    singer: 'Delicious',
    youtubeId: 'XvbBdlFDcgc',
  },
  {
    id: '13',
    albumId: '1',
    name: 'Disco Bus',
    singer: 'Stereo Bros.',
    youtubeId: 'XYqoDpKOtlA',
  },
  {
    id: '14',
    albumId: '1',
    name: 'Breathe',
    singer: 'O2',
    youtubeId: 'J8b1UFNtzQc',
  },
  {
    id: '15',
    albumId: '2',
    name: "Can't Get Over",
    singer: 'Kasino',
    youtubeId: '-wZl_ZhnVg4',
  },
  {
    id: '16',
    albumId: '2',
    name: 'What A Feeling',
    singer: 'Global Deejays',
    youtubeId: 'NzDXMTVUYBA',
  },
  {
    id: '17',
    albumId: '2',
    name: 'Axel F',
    singer: 'Crazy Frog',
    youtubeId: 'k85mRPqvMbE',
  },
  {
    id: '18',
    albumId: '2',
    name: "The Killer's Song",
    singer: 'Carolina Márquez',
    youtubeId: '2onQZgar1Z0',
  },
  {
    id: '19',
    albumId: '2',
    name: 'So Many Times',
    singer: 'Gadjo',
    youtubeId: 'H6mWxvCpgXc',
  },
  {
    id: '20',
    albumId: '2',
    name: "Lola's Theme",
    singer: 'Shapeshifters',
    youtubeId: 'XcmE6ey4aZ0',
  },
  {
    id: '21',
    albumId: '2',
    name: 'Love Believer',
    singer: 'Ivana Domenico',
    youtubeId: 'uroe_Xj-XK0',
  },
  {
    id: '22',
    albumId: '2',
    name: 'Vidas Nuevas',
    singer: 'Laura',
    youtubeId: 'asORVqvLvqU',
  },
  {
    id: '23',
    albumId: '2',
    name: 'Pon de Replay',
    singer: 'Rihanna',
    youtubeId: 'IbqogLT2RDc',
  },
  {
    id: '24',
    albumId: '2',
    name: 'Summer Lovin`',
    singer: 'Musikk feat. John Rock',
    youtubeId: 'ZQGLfvZz8Ng',
  },
  {
    id: '25',
    albumId: '2',
    name: 'Get Up',
    singer: 'DJ Ross feat. Double You',
    youtubeId: '9zCGbulTjjs',
  },
  {
    id: '26',
    albumId: '2',
    name: 'The World Is Mine',
    singer: 'David Guetta',
    youtubeId: 'QSwilU0kJF0',
  },
  {
    id: '27',
    albumId: '2',
    name: "I Wish (Skazi's Remix)",
    singer: 'Infected Mushroom',
    youtubeId: 'ffHJbkwlz7M',
  },
  {
    id: '28',
    albumId: '2',
    name: 'Free',
    singer: 'Inaya Gray',
    youtubeId: 'cbR9noYmP5k',
  },
  {
    id: '29',
    albumId: '2',
    name: "Livin'On A Prayer (DJ Tom Hopkins Remix)",
    singer: 'Dalimas',
    youtubeId: 'oupyLOdcgOw',
  },
  {
    id: '30',
    albumId: '2',
    name: 'U Got The Luv',
    singer: 'Soulfunkers',
    youtubeId: 'PvxIHaPwwEc',
  },
  {
    id: '31',
    albumId: '3',
    name: 'World, Hold On',
    singer: 'Bob Sinclar feat. Steve Edwards',
    youtubeId: 'XpdpW0z9xnQ',
  },
  {
    id: '32',
    albumId: '3',
    name: 'Your Body (Addy Van Remix)',
    singer: 'Tom Novy feat. Michael Marshall',
    youtubeId: 'o8VY-7qopSQ',
  },
  {
    id: '33',
    albumId: '3',
    name: "Movin'On (Basto! Guitarra Mix)",
    singer: 'Ian Van Dahl',
    youtubeId: '11z6PgsikaU',
  },
  {
    id: '34',
    albumId: '3',
    name: 'Shake It',
    singer: 'Kasino',
    youtubeId: '47gdnRfavuc',
  },
  {
    id: '35',
    albumId: '3',
    name: 'One Last Cry (Deep Lick Club Mix)',
    singer: 'Marina Elali',
    youtubeId: 'ibTRqwdUaN4',
  },
  {
    id: '36',
    albumId: '3',
    name: 'Shining Star (Gianluca Motta Remix)',
    singer: 'Get Far feat. Sagi Rei',
    youtubeId: '_N-AKsK4Y1w',
  },
  {
    id: '37',
    albumId: '3',
    name: 'You Gonna Want Me',
    singer: 'Tiga',
    youtubeId: 'PtwxWe7jl_c',
  },
  {
    id: '38',
    albumId: '3',
    name: 'Walking Away (Tocadisco Remix)',
    singer: 'The Egg',
    youtubeId: 'pnRycfG9sP4',
  },
  {
    id: '39',
    name: 'Same Man',
    albumId: '3',
    singer: 'Till West & DJ Delicious',
    youtubeId: 'lnz5TN2SIHc',
  },
  {
    id: '40',
    albumId: '3',
    name: "It's Too Late (Dirty South Remix)",
    singer: 'Evermore',
    youtubeId: 'IewSEJnC7cM',
  },
  {
    id: '41',
    albumId: '3',
    name: 'Electrize',
    singer: 'Komodor',
    youtubeId: 'lzDBXqliywQ',
  },
  {
    id: '42',
    albumId: '3',
    name: 'Everytime We Touch',
    singer: 'Cascada',
    youtubeId: '4G6QDNC4jPs',
  },
  {
    id: '43',
    albumId: '3',
    name: 'Clap Your Hands',
    singer: 'Ramada',
    youtubeId: 'CZpOBTztmKE',
  },
  {
    id: '44',
    albumId: '3',
    name: 'Dirty Funk',
    singer: 'Stereo Music',
    youtubeId: 'IKg4DV8CXh0',
  },
  {
    id: '45',
    albumId: '3',
    name: 'Love At First Sight',
    singer: 'Delicious',
    youtubeId: '1_DvQC33HUo',
  },
  {
    id: '46',
    albumId: '3',
    name: 'Ibiza Vibes (Guitarra Mix Edit)',
    singer: 'Paradise Island',
    youtubeId: 'v_oLvWdM3rI',
  },
  {
    id: '47',
    albumId: '3',
    name: 'Love Generation (Extended Version)',
    singer: 'Bob Sinclar feat. Steve Edwards',
    youtubeId: 'WFiVuxUmCys',
  },
  {
    id: '48',
    albumId: '4',
    name: "Give A Lil'Love",
    singer: 'Bob Sinclar feat. Steve Edwards',
    youtubeId: 'zWxfZj6fUSI',
  },
  {
    id: '49',
    albumId: '4',
    name: 'Love Is Gone (Fred Rister & Joachim Garraud Remix)',
    singer: 'David Guetta',
    youtubeId: 'Lefz4yQmwcc',
  },
  {
    id: '50',
    albumId: '4',
    name: 'Stay Around (For This) (Delicious & Till West Remix)',
    singer: 'Milk & Sugar & Ayak pres. MS2',
    youtubeId: 'Roc2pirMTMg',
  },
  {
    id: '51',
    albumId: '4',
    name: 'Lovely',
    singer: 'Tommy Vee feat. Andrea T. Mendoza',
    youtubeId: 'KXkDOwkm1WY',
  },
  {
    id: '52',
    albumId: '4',
    name: 'I Wish You Would',
    singer: 'Martijn Ten Velden',
    youtubeId: '-s8cVY1odeY',
  },
  {
    id: '53',
    albumId: '4',
    name: "Life Is Love (Nerio's Dubwork Remix)",
    singer: 'No Tone feat. Inusa Dawuda',
    youtubeId: 'Jls895rsP6g',
  },
  {
    id: '54',
    albumId: '4',
    name: 'Born Slippy',
    singer: 'DJ Joe K',
    youtubeId: '7X2W-41a2y0',
  },
  {
    id: '55',
    albumId: '4',
    name: 'Rise Up',
    singer: 'Yves Larock',
    youtubeId: 'Uu6ubD-8O48',
  },
  {
    id: '56',
    albumId: '4',
    name: 'Destination Calabria',
    singer: 'Alex Gaudino feat. Crystal Waters',
    youtubeId: 'Kq4OtRsdXls',
  },
  {
    id: '57',
    albumId: '4',
    name: "Everybody's Grooving",
    singer: 'House Boulevard',
    youtubeId: 'f58glfOCleY',
  },
  {
    id: '58',
    albumId: '4',
    name: 'Proper Education',
    singer: 'Eric Prydz feat. Floyd',
    youtubeId: 'CHyLwSmutGw',
  },
  {
    id: '59',
    albumId: '4',
    name: 'In The Dark (Dirty South Remix)',
    singer: 'DJ Tiësto feat. Christian Burns',
    youtubeId: 'L0NU3pTHwgY',
  },
  {
    id: '60',
    albumId: '4',
    name: 'Get Up (General Electric Remix)',
    singer: 'Global Deejays feat. Technotronic',
    youtubeId: 'ou2w1VIkwVI',
  },
  {
    id: '61',
    albumId: '4',
    name: 'Let Me Think About It',
    singer: 'Ida Corr vs. Fedde le Grand',
    youtubeId: '19WUwZYM7bM',
  },
  {
    id: '62',
    albumId: '4',
    name: 'Perfect (Exceeder)',
    singer: 'Mason vs. Princess Superstar',
    youtubeId: 'cXTgrHruvoo',
  },
  {
    id: '63',
    albumId: '4',
    name: 'You You You (Alex Gaudino & Jerma Extended)',
    singer: 'James Kakande',
    youtubeId: 'mQEkmWvCXbM',
  },
  {
    id: '64',
    albumId: '4',
    name: 'To Feel Your Body',
    singer: 'Hitz feat. Conroy Elis & Dominique Levack',
    youtubeId: '4CmTfwXJu5A',
  },
  {
    id: '65',
    albumId: '5',
    name: "I Don't Know Why (Viale & DJ Ross Remix)",
    singer: 'Moony',
    youtubeId: '4Q_NugNJLF0',
  },
  {
    id: '66',
    albumId: '5',
    name: 'Tomorrow Can Wait',
    singer: 'David Guetta',
    youtubeId: 'dleSC-Rg8cA',
  },
  {
    id: '67',
    albumId: '5',
    name: 'Keep On Rising',
    singer: 'Ian Carey feat. Michelle Shellers',
    youtubeId: 'KNT9kDbwocw',
  },
  {
    id: '68',
    albumId: '5',
    name: 'I Kissed a Girl (Jason Nevins Remix)',
    singer: 'Katy Perry',
    youtubeId: 'YYT_xhwQ5t8',
  },
  {
    id: '69',
    albumId: '5',
    name: 'All I Need',
    singer: 'Get Far feat. Sagi Rei',
    youtubeId: 'x7bMItpv8Hs',
  },
  {
    id: '70',
    albumId: '5',
    name: 'Set Me Free',
    singer: 'House Boulevard feat. Samara',
    youtubeId: 'fWdQhKtGJ4Y',
  },
  {
    id: '71',
    albumId: '5',
    name: 'Dance With Me (Houseshaker Remix)',
    singer: 'Saint feat. MDP',
    youtubeId: 'db_Zuho_NLE',
  },
  {
    id: '72',
    albumId: '5',
    name: 'Children',
    singer: 'Dave Darrel',
    youtubeId: '2Q5_OXPdrDU',
  },
  {
    id: '73',
    albumId: '5',
    name: 'Cry For You (Spencer & Hill Remix)',
    singer: 'September',
    youtubeId: 'iLa0Q0uayBk',
  },
  {
    id: '74',
    albumId: '5',
    name: 'What A Wonderful World',
    singer: 'Axwell & Bob Sinclar feat. Ron Carroll',
    youtubeId: 'bHTbvtTkzv0',
  },
  {
    id: '75',
    albumId: '5',
    name: 'Lose Control (DJ Tom Hopkins Remix)',
    singer: 'Double You',
    youtubeId: 'PTGpDNWbSUA',
  },
  {
    id: '76',
    albumId: '5',
    name: 'Monday',
    singer: 'Carlo Dallanese feat. Fábio Castro',
    youtubeId: '0N6bmZf_mkQ',
  },
  {
    id: '77',
    albumId: '5',
    name: 'After The Rain',
    singer: 'Fedo Mora & Camurri',
    youtubeId: 'lHn7620gEHs',
  },
  {
    id: '78',
    albumId: '5',
    name: 'Children Of The Sun (R.I.O. Remix)',
    singer: 'Yanou',
    youtubeId: 'y2LNR5_d6Wg',
  },
  {
    id: '79',
    albumId: '5',
    name: 'Shine On (Spencer & Hill Remix)',
    singer: 'R.I.O.',
    youtubeId: 'nO66gf2xydI',
  },
  {
    id: '80',
    albumId: '5',
    name: 'Turn The Tide (R.I.O. Remix)',
    singer: 'Manian',
    youtubeId: 'jTHLfH85ne8',
  },
  {
    id: '81',
    albumId: '6',
    name: 'I Gotta Feeling',
    singer: 'Black Eyed Peas',
    youtubeId: 'CwdrtwZiQ9E',
  },
  {
    id: '82',
    albumId: '6',
    name: 'When Love Takes Over',
    singer: 'David Guetta feat. Kelly Rowland',
    youtubeId: 'uTDafjfxu5c',
  },
  {
    id: '83',
    albumId: '6',
    name: 'Poker Face (Dave Audé Remix)',
    singer: 'Lady Gaga',
    youtubeId: 'yXTAbvg9XZ0',
  },
  {
    id: '84',
    albumId: '6',
    name: 'Hush Hush; Hush Hush (Dave Audé Remix)',
    singer: 'The Pussycat Dolls',
    youtubeId: 'Yg9GKDIix8k',
  },
  {
    id: '85',
    albumId: '6',
    name: 'Leave The World Behind',
    singer: 'Swedish House Mafia & Laidback Luke feat. Deborah Cox',
    youtubeId: 'Ksx1eM-gJak',
  },
  {
    id: '86',
    albumId: '6',
    name: 'Let the Bass Kick in Miami Bitch',
    singer: 'Chuckie vs. LMFAO',
    youtubeId: 'CwzavPc27KM',
  },
  {
    id: '87',
    albumId: '6',
    name: 'Infinity',
    singer: 'Guru Josh Project',
    youtubeId: '8rjpDYP9RBk',
  },
  {
    id: '88',
    albumId: '6',
    name: 'Give It to Me',
    singer: 'Alexxa',
    youtubeId: 'k9eb3w1NStI',
  },
  {
    id: '89',
    albumId: '6',
    name: 'Fiesta Loca',
    singer: 'Desaparecidos',
    youtubeId: '_MMGYPhy0fk',
  },
  {
    id: '90',
    albumId: '6',
    name: 'Brand New Day',
    singer: 'Filipe Guerra feat. Lorena Simpson',
    youtubeId: 'X7SgFfiCiiI',
  },
  {
    id: '91',
    albumId: '6',
    name: 'In The Air (Axwell Remix)',
    singer: 'TV Rock feat. Rudy',
    youtubeId: 'LXKoNleQPtk',
  },
  {
    id: '92',
    albumId: '6',
    name: 'Sun Is Coming Out',
    singer: 'DJ Memê',
    youtubeId: 'LEaNySd3a8c',
  },
  {
    id: '93',
    albumId: '6',
    name: 'Day & Night',
    singer: 'Kid Cudi feat. The Crookers',
    youtubeId: 'XSahvM08u6s',
  },
  {
    id: '94',
    albumId: '6',
    name: 'S.O.S.',
    singer: 'Ian Carey feat. Craig Smart',
    youtubeId: '7cVCEmvR7y4',
  },
  {
    id: '95',
    albumId: '6',
    name: 'Destiny',
    singer: 'DJ Tom Hopkins feat. Samara',
    youtubeId: 'mwxYUgGmw4w',
  },
  {
    id: '96',
    albumId: '6',
    name: 'I Feel So Free',
    singer: 'Spyzer',
    youtubeId: 'hDEdadLye_k',
  },
  {
    id: '97',
    albumId: '7',
    name: 'One',
    singer: 'Swedish House Mafia feat. Pharrell',
    youtubeId: 'iJld9Ra1OBQ',
  },
  {
    id: '98',
    albumId: '7',
    name: "Gettin'Over You",
    singer: 'David Guetta feat. Fergie & LMFAO',
    youtubeId: 'Jn2OAS1K3ZY',
  },
  {
    id: '99',
    albumId: '7',
    name: 'California Gurls',
    singer: 'Katy Perry feat. Snoop Dogg',
    youtubeId: 'tRiE-YjHHKE',
  },
  {
    id: '100',
    albumId: '7',
    name: "I'm In Love (I Wanna Do It)",
    singer: 'Alex Gaudino',
    youtubeId: 'bKDsur3lgaI',
  },
  {
    id: '101',
    albumId: '7',
    name: 'Stereo Love (Molella Radio Edit)',
    singer: 'Edward Maya & Vika Jigulina',
    youtubeId: 'TqIydDZJ2xg',
  },
  {
    id: '102',
    albumId: '7',
    name: "We No Speak Americano (Tu Vuò Fà L'Americano)",
    singer: 'Yolanda Be Cool vs. Dcup',
    youtubeId: 'B1XWcBIicWs',
  },
  {
    id: '103',
    albumId: '7',
    name: 'Tik Tok (Fred Falke Remix)',
    singer: 'Ke$ha',
    youtubeId: 'RC6Jwmt91rs',
  },
  {
    id: '104',
    albumId: '7',
    name: "Club Can't Handle Me",
    singer: 'Flo Rida feat. David Guetta',
    youtubeId: 'dS8WyNVHVyA',
  },
  {
    id: '105',
    albumId: '7',
    name: 'Not Giving Up On Love',
    singer: 'Armim Van Buuren vs. Sophie Ellis-Bextor',
    youtubeId: 'D2LHV40dJsc',
  },
  {
    id: '106',
    albumId: '7',
    name: 'Live It Up',
    singer: 'Ali Pierre',
    youtubeId: 'pv242bkj7mo',
  },
  {
    id: '107',
    albumId: '7',
    name: "That's My Name",
    singer: 'Akcent',
    youtubeId: 'SBQPv3A9XIs',
  },
  {
    id: '108',
    albumId: '7',
    name: 'Summer Lie',
    singer: 'Eliza G.',
    youtubeId: 'ovwv4TWN6-E',
  },
  {
    id: '109',
    albumId: '7',
    name: "I Don't Know What To Do",
    singer: " Tiko's Groove feat. Gosha",
    youtubeId: 'ag-5VzK_PtY',
  },
  {
    id: '110',
    albumId: '7',
    name: 'Follow You',
    singer: 'Desaparecidos',
    youtubeId: '81zf9pr3MGY',
  },
  {
    id: '111',
    albumId: '7',
    name: 'Release Me',
    singer: 'Tv Rock & Zoe Badwi',
    youtubeId: 'fHm9nJurkG0',
  },
  {
    id: '112',
    albumId: '7',
    name: 'Hot',
    singer: 'Inna',
    youtubeId: 'K15zuILXkP0',
  },
  {
    id: '113',
    albumId: '7',
    name: "Hey Hey (DF's Attention Remix)",
    singer: 'Dennis Ferrer',
    youtubeId: 'opPHYq8cE1E',
  },
  {
    id: '114',
    albumId: '7',
    name: 'Falling for U',
    singer: 'Mister Jam feat. Wanessa',
    youtubeId: 'n_pQR8TBa9g',
  },
  {
    id: '115',
    albumId: '8',
    name: 'Save The World',
    singer: 'Swedish House Mafia feat. John Martin',
    youtubeId: 'bYLTh-oyrk8',
  },
  {
    id: '116',
    albumId: '8',
    name: 'Give Me Everything',
    singer: 'Pitbull feat. Ne-Yo, Afrojack & Nayer',
    youtubeId: '2tCpkDh_Zto',
  },
  {
    id: '117',
    albumId: '8',
    name: 'Beautiful People',
    singer: 'Chris Brown feat. Benny Benassi',
    youtubeId: 'Yi-2cgzNz_U',
  },
  {
    id: '118',
    albumId: '8',
    name: 'Take Over Control',
    singer: 'Afrojack feat. Eva Simons',
    youtubeId: 'PpFOIpadpVM',
  },
  {
    id: '119',
    albumId: '8',
    name: 'Cry (Just A Little)',
    singer: 'Bingo Players',
    youtubeId: 'cZL6bqFLJi0',
  },
  {
    id: '120',
    albumId: '8',
    name: 'Made Of (Radio Edit)',
    singer: 'Nause',
    youtubeId: 'efC8hxHJ7-w',
  },
  {
    id: '121',
    albumId: '8',
    name: 'Dynamite',
    singer: 'Taio Cruz',
    youtubeId: 'OHL8Z6I0-04',
  },
  {
    id: '122',
    albumId: '8',
    name: 'Seek Bromance',
    singer: 'Tim Berg',
    youtubeId: 'l2l_duTwhtc',
  },
  {
    id: '123',
    albumId: '8',
    name: 'Welcome To St. Tropez',
    singer: 'DJ Antoine vs. Timati feat. Kalenna',
    youtubeId: 'bWxDjxPn-8c',
  },
  {
    id: '124',
    albumId: '8',
    name: 'I Wanna Go',
    singer: 'Britney Spears',
    youtubeId: 'tdj7LUf-2C0',
  },
  {
    id: '125',
    albumId: '8',
    name: 'You Make Me Feel',
    singer: 'Cobra Starship feat. Sabi',
    youtubeId: 'MXYggIbS0KE',
  },
  {
    id: '126',
    albumId: '8',
    name: 'Mr. Saxobeat',
    singer: 'Alexandra Stan',
    youtubeId: 'AJS-BshkE28',
  },
  {
    id: '127',
    albumId: '8',
    name: 'Barbra Streisand',
    singer: 'Duck Sauce',
    youtubeId: 'SJ6LKLGHjUU',
  },
  {
    id: '128',
    albumId: '8',
    name: 'Walkin’ On Air (Burn)',
    singer: 'Mister Jam feat. Ali Pierre & King TEF',
    youtubeId: 'aDtT4Rf5WiY',
  },
  {
    id: '129',
    albumId: '8',
    name: 'What A Feeling',
    singer: 'Alex Gaudino feat. Kelly Rowland',
    youtubeId: '7eB7pQ5eqDw',
  },
  {
    id: '130',
    albumId: '8',
    name: 'Got Me Going Over',
    singer: 'Ask2Quit feat. Colonel Red',
    youtubeId: '2d4WzG8nW4U',
  },
  {
    id: '131',
    albumId: '8',
    name: 'Show Me',
    singer: 'Jessica Sutta',
    youtubeId: 'ANS-c3KipYU',
  },
  {
    id: '132',
    albumId: '8',
    name: "Don't Wanna Go Home [sample: Show me Love]",
    singer: 'Jason Derülo',
    youtubeId: '6CDX04Gbl2g',
  },
  {
    id: '133',
    albumId: '9',
    name: "Let's Go",
    singer: 'Calvin Harris feat. Ne-Yo',
    youtubeId: 'Be6qWOd94FI',
  },
  {
    id: '134',
    albumId: '9',
    name: "Don't You Worry Child",
    singer: 'Swedish House Mafia feat. John Martin',
    youtubeId: '_TAJsIwlze8',
  },
  {
    id: '135',
    albumId: '9',
    name: "Don't Stop the Party",
    singer: 'Pitbull feat. TJR',
    youtubeId: 'yYLTGtBk5Dc',
  },
  {
    id: '136',
    albumId: '9',
    name: 'Calling (Lose My Mind)',
    singer: 'Sebastian Ingrosso feat. Alesso & Ryan Tedder',
    youtubeId: 'vvV9sKR-OG8',
  },
  {
    id: '137',
    albumId: '9',
    name: 'Who',
    singer: 'Tujamo & Plastik Funk',
    youtubeId: 'nSYRU1eUVIY',
  },
  {
    id: '138',
    albumId: '9',
    name: 'Golden People',
    singer: 'Mister Jam feat. Jacq & King TEF',
    youtubeId: '7u3REt7LcY8',
  },
  {
    id: '139',
    albumId: '9',
    name: "Can't Stop Me",
    singer: 'Afrojack & Shermanology',
    youtubeId: 'JnxYFZXhJPA',
  },
  {
    id: '140',
    albumId: '9',
    name: 'How We Do (Party) - Juhola & Denavi Remix',
    singer: 'Rita Ora',
    youtubeId: 'ckBlXeBkSG8',
  },
  {
    id: '141',
    albumId: '9',
    name: 'Spectrum',
    singer: 'Zedd feat. Matthew Koma',
    youtubeId: 'dzP8ID8kLVg',
  },
  {
    id: '142',
    albumId: '9',
    name: 'Famous Before 5',
    singer: 'R-Go feat. Nando Vedder',
    youtubeId: 'DcjHcqYbm1A',
  },
  {
    id: '143',
    albumId: '9',
    name: 'One Day (Reckoning Song)',
    singer: 'Asaf Avidan',
    youtubeId: 'w5dsmSviCvo',
  },
  {
    id: '144',
    albumId: '9',
    name: "I Can't Get Nothing",
    singer: " Tiko's Groove feat. Gosha",
    youtubeId: 'CclIcYvTzs0',
  },
  {
    id: '145',
    albumId: '9',
    name: 'The Night Out',
    singer: 'Martin Solveig',
    youtubeId: 'AV-8EOJGzo8',
  },
  {
    id: '146',
    albumId: '9',
    name: 'I Want You Back',
    singer: 'DJ Joe K feat. Jerique Allan',
    youtubeId: 'x_Y0PBCB8es',
  },
  {
    id: '147',
    albumId: '9',
    name: 'Take You Higher',
    singer: 'Goodwill & Hook N Sling',
    youtubeId: 'pRPX-aVa5t8',
  },
  {
    id: '148',
    albumId: '9',
    name: 'Ma Chérie',
    singer: 'DJ Antoine feat. The Beat Shakers',
    youtubeId: 'm9bll22wYRc',
  },
  {
    id: '149',
    albumId: '10',
    name: 'I Love It (Cobra Starship Remix)',
    singer: 'Icona Pop feat. Charli XCX',
    youtubeId: 'NxibYrEsjt0',
  },
  {
    id: '150',
    albumId: '10',
    name: 'Locked Out of Heaven',
    singer: 'Bruno Mars',
    youtubeId: 'yECcVa6tsX8',
  },
  {
    id: '151',
    albumId: '10',
    name: 'Sweet Nothing',
    singer: 'Calvin Harris feat. Florence Welch',
    youtubeId: 'TlOeXk_VGeY',
  },
  {
    id: '152',
    albumId: '10',
    name: 'This Is What It Feels Like',
    singer: 'Armin Van Buuren feat. Trevor Guthrie',
    youtubeId: 'xkUaOM514XI',
  },
  {
    id: '153',
    albumId: '10',
    name: 'Never Say Goodbye',
    singer: 'Hardwell & Dyro feat. Bright Lights',
    youtubeId: 'gpbi0XoaxLw',
  },
  {
    id: '154',
    albumId: '10',
    name: 'Summer Moonlight',
    singer: 'Bob Sinclar feat. Bem Delay',
    youtubeId: 'et4PhC7OBaQ',
  },
  {
    id: '155',
    albumId: '10',
    name: 'Keep Running',
    singer: 'Marcelo CIC feat. Benjamin K',
    youtubeId: 'nA8pWMywxas',
  },
  {
    id: '156',
    albumId: '10',
    name: 'No Place Like Home',
    singer: 'Mync & Senadee',
    youtubeId: 'iVxpqFCZ-IA',
  },
  {
    id: '157',
    albumId: '10',
    name: 'Sunrise (Won’t Get Lost)',
    singer: 'The Aston Shufle & Tommy Trash',
    youtubeId: 'PeXy7ujZpHg',
  },
  {
    id: '158',
    albumId: '10',
    name: 'Alive',
    singer: 'Krewella',
    youtubeId: 'uELBOqouvng',
  },
  {
    id: '159',
    albumId: '10',
    name: 'Give All Now',
    singer: " Tiko's Groove feat. Gosha",
    youtubeId: 'H5NRA7TpjDo',
  },
  {
    id: '160',
    albumId: '10',
    name: 'Call Me a Spaceman',
    singer: 'Hardwell feat. Mitch Crown',
    youtubeId: 'Q7raSefskX8',
  },
  {
    id: '161',
    albumId: '10',
    name: 'Heartbeat',
    singer: 'Mr. Jam feat. Chris Willis',
    youtubeId: 'y7SHAPyWDvg',
  },
  {
    id: '162',
    albumId: '10',
    name: 'When I Turn Off The Lights',
    singer: 'Cuti DJ feat. D’Twice',
    youtubeId: '-ea25o3HBEs',
  },
  {
    id: '163',
    albumId: '10',
    name: 'Warrior',
    singer: 'Luciano Roffer, R-Go & Ester',
    youtubeId: '5pWG7rZaRWA',
  },
  {
    id: '164',
    albumId: '10',
    name: 'Best of You',
    singer: " Vee Brondi & Marcelo D'Sá",
    youtubeId: 'DVPcwFR_2ZA',
  },
  {
    id: '165',
    albumId: '10',
    name: 'Ready',
    singer: 'Anthony Garcia',
    youtubeId: 'T3ivAS0ZQ8o',
  },
  {
    id: '166',
    albumId: '11',
    name: 'Shot Me Down',
    singer: 'David Guetta feat. Skylar Grey',
    youtubeId: 'mMmqjnwQlVc',
  },
  {
    id: '167',
    albumId: '11',
    name: 'Rather Be',
    singer: 'Clean Bandit feat. Jess Glynne',
    youtubeId: 'jUjDcqdvCrk',
  },
  {
    id: '168',
    albumId: '11',
    name: 'A Sky Full of Stars',
    singer: 'Avicii & Coldplay',
    youtubeId: 'FAsOx3O4tdk',
  },
  {
    id: '169',
    albumId: '11',
    name: 'Dare You',
    singer: 'Hardwell feat. Matthew Koma',
    youtubeId: 'fKv6sIsUdn8',
  },
  {
    id: '170',
    albumId: '11',
    name: 'Howl at the Moon',
    singer: 'Stadiumx & Taylr Renne',
    youtubeId: 'zSLKGKDuCYg',
  },
  {
    id: '171',
    albumId: '11',
    name: 'Show Me Love',
    singer: 'Michael Mind Project',
    youtubeId: '1R9_AWAEfMA',
  },
  {
    id: '172',
    albumId: '11',
    name: 'Light It Up',
    singer: 'DJ Antoine',
    youtubeId: 'ReqpE9Cj94A',
  },
  {
    id: '173',
    albumId: '11',
    name: 'We Are Free',
    singer: 'Mister Jam feat. Johnny Franco',
    youtubeId: '8bFXTm3K07M',
  },
  {
    id: '174',
    albumId: '11',
    name: 'Beautiful Daylight',
    singer: 'Vee Brondi & Terri B!',
    youtubeId: '3FPxEoevkpg',
  },
  {
    id: '175',
    albumId: '11',
    name: 'Revolution (Audien Remix)',
    singer: 'R3hab, Nervo & Ummet Ozcan',
    youtubeId: 'yTKWDwomHbA',
  },
  {
    id: '176',
    albumId: '11',
    name: 'Wicked Wonderland',
    singer: 'Martin Tungevaag',
    youtubeId: 'g6IHW2a_UCA',
  },
  {
    id: '177',
    albumId: '11',
    name: 'Celebrate Life',
    singer: 'Cuti DJ feat. Marquinho Osócio',
    youtubeId: 'YK3bdEDAPcw',
  },
  {
    id: '178',
    albumId: '11',
    name: 'The Bass',
    singer: 'Tom Hopkins & Anthony Garcia',
    youtubeId: '3kgBdjVDoyk',
  },
  {
    id: '179',
    albumId: '11',
    name: 'We Were Young',
    singer: 'DVBBS',
    youtubeId: 'Vn4B6TEWlB4',
  },
  {
    id: '180',
    albumId: '12',
    name: 'Blame',
    singer: 'Calvin Harris feat. John Newman',
    youtubeId: '4Auq31UscV4',
  },
  {
    id: '181',
    albumId: '12',
    name: 'Tremor',
    singer: 'Dimitri Vegas & Like Mike feat. Martin Garrix',
    youtubeId: 'WvFjpXIGcj4',
  },
  {
    id: '182',
    albumId: '12',
    name: 'Intoxicated',
    singer: 'Martin Solveig vs. GTA',
    youtubeId: 'diw3ZLcalUI',
  },
  {
    id: '183',
    albumId: '12',
    name: 'Cheerleader (Felix Jaehn remix)',
    singer: 'Omi',
    youtubeId: 'NYVWj5cs_P8',
  },
  {
    id: '184',
    albumId: '12',
    name: 'Runaway (U & I)',
    singer: 'Galantis',
    youtubeId: 'yPGGUhUXWrw',
  },
  {
    id: '185',
    albumId: '12',
    name: "Can't Stop Playing",
    singer: 'Dr. Kucho! & Gregor Salto',
    youtubeId: '9sadCdOfa6o',
  },
  {
    id: '186',
    albumId: '12',
    name: 'Sally',
    singer: 'Hardwell feat. Harrison',
    youtubeId: '12AFWW47r_w',
  },
  {
    id: '187',
    albumId: '12',
    name: 'Gold Skies (Tiësto Remix)',
    singer: 'Sander Van Doorn, Martin Garrix & DVBBS feat. Alessia',
    youtubeId: 'x6hkZ1r420Y',
  },
  {
    id: '188',
    albumId: '12',
    name: 'Bounce Generation',
    singer: 'TJR & VINAI',
    youtubeId: 'PWBwA75SXmI',
  },
  {
    id: '189',
    albumId: '12',
    name: 'Prayer in C',
    singer: 'Lilly Wood & The Prick and Robin Schulz',
    youtubeId: 'tZUVgYxSlGs',
  },
  {
    id: '190',
    albumId: '12',
    name: 'Waves',
    singer: 'Mr. Probz',
    youtubeId: 'zjBbi6AFG3I',
  },
  {
    id: '191',
    albumId: '12',
    name: 'Sweets (Soda Pop)',
    singer: 'Fox Stevenson',
    youtubeId: '3PApJ5XekBM',
  },
  {
    id: '192',
    albumId: '12',
    name: 'The Night',
    singer: '3LAU & Nom de Strip feat. Estelle',
    youtubeId: 'ZFGNx7T_qTw',
  },
  {
    id: '193',
    albumId: '12',
    name: 'Virus (How About Now)',
    singer: 'Martin Garrix & MOTi',
    youtubeId: 'Hr5F8I_OqE8',
  },
  {
    id: '194',
    albumId: '13',
    name: "Don't Let Me Down",
    singer: 'The Chainsmokers feat. Daya',
    youtubeId: 'Y2rtFgMqK1A',
  },
  {
    id: '195',
    albumId: '13',
    name: 'In the Name of Love',
    singer: 'Martin Garrix feat. Bebe Rexha',
    youtubeId: '-URUQz7MkeY',
  },
  {
    id: '196',
    albumId: '13',
    name: 'Perfect Strangers',
    singer: 'Jonas Blue feat. JP Cooper',
    youtubeId: '_RgIafMSeIY',
  },
  {
    id: '197',
    albumId: '13',
    name: 'Give It All Up',
    singer: 'WAO feat. Mikkel Solnado',
    youtubeId: 'KDPbWr6jw0o',
  },
  {
    id: '198',
    albumId: '13',
    name: 'Young Again',
    singer: 'Hardwell feat. Chris Jones',
    youtubeId: 'zvbDWKnAMl8',
  },
  {
    id: '199',
    albumId: '13',
    name: 'Paradise',
    singer: 'Benny Benassi & Chris Brown',
    youtubeId: 'AhtYBVYC8BY',
  },
  {
    id: '200',
    albumId: '13',
    name: '7 Years',
    singer: 'Kiwi Bird',
    youtubeId: 'J1qkUv8cHTk',
  },
  {
    id: '201',
    albumId: '13',
    name: 'The Ocean',
    singer: 'Mike Perry feat. Shy Martin',
    youtubeId: '0T74nuJ0Pgk',
  },
  {
    id: '202',
    albumId: '13',
    name: 'Fast Car',
    singer: 'NLKD',
    youtubeId: 's6IeVVMvP6k',
  },
  {
    id: '203',
    albumId: '13',
    name: 'She Knows',
    singer: 'Elekfantz',
    youtubeId: 'y47ZR6p-7iw',
  },
  {
    id: '204',
    albumId: '13',
    name: 'Here Without You',
    singer: 'The Squadz',
    youtubeId: 'aAu3t3b43To',
  },
  {
    id: '205',
    albumId: '13',
    name: 'Nightlife',
    singer: 'D.I.B feat. Nathan Brumley',
    youtubeId: 'L0U-Zn1MceY',
  },
  {
    id: '206',
    albumId: '13',
    name: 'Turn It Up',
    singer: 'Naza Brothers',
    youtubeId: 'Ak46UUzdneU',
  },
  {
    id: '207',
    albumId: '13',
    name: 'Troy',
    singer: 'Ftampa & WAO',
    youtubeId: 'AouJJj9Gm7I',
  },
  {
    id: '208',
    albumId: '14',
    name: 'Your Power',
    singer: 'WAO feat. Gannah',
    youtubeId: 'LGKY550oenI',
  },
  {
    id: '209',
    albumId: '14',
    name: 'One Nation',
    singer: 'D.I.B. feat. Luizor Eim',
    youtubeId: 'eqwPAnk3W5k',
  },
  {
    id: '210',
    albumId: '14',
    name: 'Breakup Song',
    singer: 'De Hofnar feat. Son of Patricia',
    youtubeId: 'vnwxH7_1d_Y',
  },
  {
    id: '211',
    albumId: '14',
    name: 'Infinito Particular (Bhaskar Remix)',
    singer: 'Silva',
    youtubeId: 'OMTzbY3E4QA',
  },
  {
    id: '212',
    albumId: '14',
    name: 'Rising Sun',
    singer: 'Goldfish & Pontifexx feat. Gustavo Bertoni',
    youtubeId: 'AMfPq2Lmh7I',
  },
  {
    id: '213',
    albumId: '14',
    name: 'Vem Quente Que Eu Estou Fervendo',
    singer: 'Rivas (Br) vs Danne feat. Breno Miranda',
    youtubeId: 'KCGYElNM1LY',
  },
  {
    id: '214',
    albumId: '14',
    name: 'Summer Love',
    singer: 'Chemical Surf feat. Jake Reese',
    youtubeId: 'oIIug614Hig',
  },
  {
    id: '215',
    albumId: '14',
    name: 'Cold Heart',
    singer: 'Bhaskar vs Gabriel Boni feat. Layna',
    youtubeId: 'zCShlmAY3ow',
  },
  {
    id: '216',
    albumId: '14',
    name: 'Wicked Games',
    singer: 'Vee Groove feat. Luciana Gaspar',
    youtubeId: 'iBf5rLnRrG0',
  },
  {
    id: '217',
    albumId: '14',
    name: 'Paradise',
    singer: 'Kenshin & Mojjo feat. Marcelo Braga',
    youtubeId: 'YkAHk4muUU8',
  },
  {
    id: '218',
    albumId: '14',
    name: 'Found U',
    singer: 'Dimmi feat. Zeeba',
    youtubeId: 'ZisCLmKB6Uk',
  },
  {
    id: '219',
    albumId: '14',
    name: 'In My Soul',
    singer: 'WAO feat. Kamatos',
    youtubeId: '4v4_xpFuKO8',
  },
  {
    id: '220',
    albumId: '14',
    name: "I'm Not Dreaming",
    singer: 'D.I.B. feat. Sam Alves',
    youtubeId: '7fL2fojBZ5c',
  },
  {
    id: '221',
    albumId: '14',
    name: 'She Says',
    singer: 'Nato Medrado',
    youtubeId: 'hneDTNSF1Xc',
  },
  {
    id: '222',
    albumId: '15',
    name: 'Abraço Forte',
    singer: 'Bhaskar feat. Hungria Hip Hop',
    youtubeId: '1XPJNFUS380',
  },
  {
    id: '223',
    albumId: '15',
    name: 'Nosso Amor Virou Canção',
    singer: 'Ralk, Make U Sweat feat. Guga Sabatiê',
    youtubeId: 'Vdr9zGgyA7w',
  },
  {
    id: '224',
    albumId: '15',
    name: "When You're Alone",
    singer: 'Altermauz feat. Pontifexx',
    youtubeId: 'BHGYqJhUVIc',
  },
  {
    id: '225',
    albumId: '15',
    name: 'Addicted',
    singer: 'Doublez, Guz Zanotto feat. Ol.C',
    youtubeId: 'Nno5aumLBDI',
  },
  {
    id: '226',
    albumId: '15',
    name: 'Let You Go',
    singer: 'Mojjo',
    youtubeId: 'knnakkhbWb4',
  },
  {
    id: '227',
    albumId: '15',
    name: 'Pura Invenção',
    singer: 'Brazza Squad, Cool Keedz feat. Leo S',
    youtubeId: 'g0qUN77K3ec',
  },
  {
    id: '228',
    albumId: '15',
    name: 'Cuidado',
    singer: 'Gaab feat.Ralk',
    youtubeId: 'tWLfPlpRx5w',
  },
  {
    id: '229',
    albumId: '15',
    name: 'Fica Tudo Bem',
    singer: 'Silva, Bhaskar feat. Anitta',
    youtubeId: 'd7C6ID964Ec',
  },
  {
    id: '230',
    albumId: '15',
    name: 'All Night',
    singer: 'Woo2tech, Arcuri feat. Weldon',
    youtubeId: 'Sc38GMadUUw',
  },
  {
    id: '231',
    albumId: '15',
    name: 'First Love',
    singer: 'D.I.B',
    youtubeId: 'fNQRfP9Dggs',
  },
  {
    id: '232',
    albumId: '15',
    name: 'Devotion',
    singer: 'Pontifexx, Foreign',
    youtubeId: 'JfpCKZLZ4cQ',
  },
  {
    id: '233',
    albumId: '15',
    name: 'Like Dis',
    singer: 'Volac feat. Gustavo Mota',
    youtubeId: 'jUkC1yfwrgA',
  },
  {
    id: '234',
    albumId: '15',
    name: 'Tô Feliz (Matei O Presidente) 2',
    singer: 'Gabriel O Pensador feat. Chemical Surf, DJ Memê',
    youtubeId: 'aV8-NujWpig',
  },
  {
    id: '235',
    albumId: '15',
    name: 'Think Fast',
    singer: 'Liu',
    youtubeId: '1nHX3ERF4d4',
  },
  {
    id: '236',
    albumId: '16',
    name: 'Surreal (feat. Vitório)',
    singer: 'Mojjo',
    youtubeId: 'n35sGPNoKP4',
  },
  {
    id: '237',
    albumId: '16',
    name: 'Show Me Love',
    singer: 'Sandeille',
    youtubeId: 'rqmWzMCKL28',
  },
  {
    id: '238',
    albumId: '16',
    name: 'Pensa Em Mim',
    singer: 'Ralk',
    youtubeId: 'uNEF8BryRfg',
  },
  {
    id: '239',
    albumId: '16',
    name: 'Mood',
    singer: 'Samhara',
    youtubeId: 'wl6k-UFZkx8',
  },
  {
    id: '240',
    albumId: '16',
    name: "I'm the One",
    singer: 'Mojjo',
    youtubeId: 'vAv1KBQYNlk',
  },
  {
    id: '241',
    albumId: '16',
    name: 'Touch Me',
    singer: 'Bhaskar',
    youtubeId: 'HOyPNJX1qYI',
  },
  {
    id: '242',
    albumId: '16',
    name: 'Fallow Rivers',
    singer: 'Salk',
    youtubeId: '_3Eq_-lXcuQ',
  },
  {
    id: '243',
    albumId: '16',
    name: 'Crazy In Ibiza',
    singer: 'Jatlag Music',
    youtubeId: 'EOD-AOgnxb4',
  },
  {
    id: '244',
    albumId: '16',
    name: 'Marra Cash',
    singer: 'Samhara',
    youtubeId: '4Z-Ql2Y0YvE',
  },
  {
    id: '245',
    albumId: '16',
    name: 'Alive',
    singer: 'VINNE',
    youtubeId: 'A8zXFNacpkE',
  },
  {
    id: '246',
    albumId: '16',
    name: 'Lost in True Devotion',
    singer: 'Clubbers',
    youtubeId: 'IGJo0JSXqEU',
  },
  {
    id: '247',
    albumId: '16',
    name: "It's All About",
    singer: 'Rooftime',
    youtubeId: 'yTKUo6zd_gc',
  },
  {
    id: '248',
    albumId: '16',
    name: 'My Way (feat. drecopy)',
    singer: 'Zucchi',
    youtubeId: 'cb6n814YD88',
  },
  {
    id: '249',
    albumId: '16',
    name: 'Belong',
    singer: 'Zerb',
    youtubeId: 'tDNKSbGhlV8',
  },
]
